/**
 * Provider-agnostic AI contract.
 *
 * Business logic (modules, server actions, route handlers) only ever speaks
 * these types. Provider adapters translate them to vendor wire formats — see
 * docs/adr/0002-ai-gateway.md.
 */

export type AIRole = "system" | "user" | "assistant" | "tool";

export interface AIToolCall {
  /** Provider-issued id when available, otherwise generated by the adapter. */
  id: string;
  name: string;
  /** JSON-encoded arguments, exactly as produced by the model. */
  arguments: string;
}

export interface AIMessage {
  role: AIRole;
  content: string;
  /** Tool calls issued by the assistant in a previous turn (role "assistant"). */
  toolCalls?: AIToolCall[];
  /** For role "tool": id of the tool call this message answers. */
  toolCallId?: string;
  /** For role "tool": name of the tool that produced this result. */
  name?: string;
}

export interface AIToolDefinition {
  name: string;
  description: string;
  /** JSON Schema describing the tool arguments. */
  parameters: Record<string, unknown>;
}

export interface AICompletionRequest {
  messages: AIMessage[];
  tools?: AIToolDefinition[];
  temperature?: number;
  maxOutputTokens?: number;
  /** Ask the provider for a JSON object response when supported. */
  jsonMode?: boolean;
  /** Override the provider's default model for this call. */
  model?: string;
  signal?: AbortSignal;
}

export interface AIUsage {
  inputTokens: number;
  outputTokens: number;
}

export type AIFinishReason = "stop" | "length" | "tool_calls" | "content_filter" | "unknown";

export interface AICompletionResult {
  text: string;
  toolCalls: AIToolCall[];
  finishReason: AIFinishReason;
  usage?: AIUsage;
  model: string;
  provider: string;
}

export type AIStreamEvent =
  | { type: "text-delta"; text: string }
  | { type: "tool-call"; toolCall: AIToolCall }
  | { type: "finish"; finishReason: AIFinishReason; usage?: AIUsage };

/** Injectable fetch for unit testing adapters without network access. */
export type FetchLike = typeof fetch;
